/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Modelo1RouteImport } from './routes/modelo-1'
import { Route as Modelo2RouteImport } from './routes/modelo-2'
import { Route as Modelo3RouteImport } from './routes/modelo-3'
import { Route as Modelo4RouteImport } from './routes/modelo-4'
import { Route as ObrigadoRouteImport } from './routes/obrigado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Modelo1Route = Modelo1RouteImport.update({
  id: '/modelo-1',
  path: '/modelo-1',
  getParentRoute: () => rootRouteImport,
} as any)
const Modelo2Route = Modelo2RouteImport.update({
  id: '/modelo-2',
  path: '/modelo-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Modelo3Route = Modelo3RouteImport.update({
  id: '/modelo-3',
  path: '/modelo-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Modelo4Route = Modelo4RouteImport.update({
  id: '/modelo-4',
  path: '/modelo-4',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modelo-1': typeof Modelo1Route
  '/modelo-2': typeof Modelo2Route
  '/modelo-3': typeof Modelo3Route
  '/modelo-4': typeof Modelo4Route
  '/obrigado': typeof ObrigadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modelo-1': typeof Modelo1Route
  '/modelo-2': typeof Modelo2Route
  '/modelo-3': typeof Modelo3Route
  '/modelo-4': typeof Modelo4Route
  '/obrigado': typeof ObrigadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modelo-1': typeof Modelo1Route
  '/modelo-2': typeof Modelo2Route
  '/modelo-3': typeof Modelo3Route
  '/modelo-4': typeof Modelo4Route
  '/obrigado': typeof ObrigadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/modelo-1' | '/modelo-2' | '/modelo-3' | '/modelo-4' | '/obrigado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modelo-1' | '/modelo-2' | '/modelo-3' | '/modelo-4' | '/obrigado'
  id:
    | '__root__'
    | '/'
    | '/modelo-1'
    | '/modelo-2'
    | '/modelo-3'
    | '/modelo-4'
    | '/obrigado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Modelo1Route: typeof Modelo1Route
  Modelo2Route: typeof Modelo2Route
  Modelo3Route: typeof Modelo3Route
  Modelo4Route: typeof Modelo4Route
  ObrigadoRoute: typeof ObrigadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo-1': {
      id: '/modelo-1'
      path: '/modelo-1'
      fullPath: '/modelo-1'
      preLoaderRoute: typeof Modelo1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo-2': {
      id: '/modelo-2'
      path: '/modelo-2'
      fullPath: '/modelo-2'
      preLoaderRoute: typeof Modelo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo-3': {
      id: '/modelo-3'
      path: '/modelo-3'
      fullPath: '/modelo-3'
      preLoaderRoute: typeof Modelo3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo-4': {
      id: '/modelo-4'
      path: '/modelo-4'
      fullPath: '/modelo-4'
      preLoaderRoute: typeof Modelo4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Modelo1Route: Modelo1Route,
  Modelo2Route: Modelo2Route,
  Modelo3Route: Modelo3Route,
  Modelo4Route: Modelo4Route,
  ObrigadoRoute: ObrigadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
